branch-defaults:
  tempUser:
    environment: NodeVer-env
environment-defaults:
  NodeVer-env:
    branch: null
    repository: null
global:
  application_name: nodeVer
  default_ec2_keyname: poorkingKeypair
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
