branch-defaults:
  master:
    environment: Gfdgdgdgdfg-env
environment-defaults:
  Gfdgdgdgdfg-env:
    branch: null
    repository: null
global:
  application_name: gfdgdgdgdfg
  default_ec2_keyname: poorkingKeypair
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
